name: commute-match-maker-backend
services:
- name: api
  source_dir: /
  github:
    repo: sathudeva7/Commute-Match-Maker-BE
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: MONGODB_URI
    value: YOUR_MONGODB_CONNECTION_STRING
    type: SECRET
  - key: JWT_SECRET
    value: YOUR_JWT_SECRET
    type: SECRET 